import type { ProofSnapshot } from "../../application/proof/snapshot";

/**
 * Deterministic diligence summary derived from the SAME ProofSnapshot the
 * Evidence surface renders — no second fetch, no new truth. Markdown is
 * generated in a fixed section order from sorted DTO tables, so identical
 * snapshots produce identical bytes.
 *
 * This is a PRELIMINARY DECISION-SUPPORT SUMMARY. It is not legal,
 * architectural, or financial certification, and the document says so.
 */

const AUTHORITY_LABEL: Record<string, string> = {
  ADOPTED_CODE: "adopted code",
  OFFICIAL_GIS: "official GIS",
  OFFICIAL_CITY_TOOL: "official city tool",
  OFFICIAL_CITY_REFERENCE: "official city reference",
  PROPERTY_SELF_REPORTED: "property self-reported",
  SECONDARY: "secondary",
};

function quantityText(value: { value: number; unit: string } | null): string {
  if (!value) return "—";
  return `${value.value.toLocaleString("en-US")} ${value.unit}`;
}

/** "X (authority)" — omitting the authority label when the title already says it. */
function sourceLabel(title: string, authority: string): string {
  const label = AUTHORITY_LABEL[authority] ?? authority;
  return title.toLowerCase().includes(label.toLowerCase()) ? title : `${title} (${label})`;
}

export function buildDiligenceSummary(
  snapshot: ProofSnapshot,
  selectedScenarioId: string | null,
): string {
  const scenario =
    snapshot.scenarios.find((entry) => entry.id === selectedScenarioId) ?? snapshot.scenarios[0];
  const certificate = scenario
    ? snapshot.certificates.find((entry) => entry.id === scenario.certificateId)
    : undefined;
  const lines: string[] = [];

  lines.push("# Acrevia — Preliminary Development Feasibility Summary");
  lines.push("");
  lines.push(
    "> Preliminary decision-support summary generated by Acrevia from captured public evidence, user-declared mission rules, and deterministic computation. **Not legal, architectural, or financial certification.** Assumptions and unresolved expert questions are listed below and must be resolved by qualified professionals before any decision.",
  );
  lines.push("");

  // Property -----------------------------------------------------------------
  lines.push("## Property");
  lines.push("");
  lines.push(`- Query: ${snapshot.identity.query}`);
  if (snapshot.identity.matchedAddress) lines.push(`- Matched address: ${snapshot.identity.matchedAddress}`);
  lines.push(`- Project: ${snapshot.identity.projectId} (parcel ${snapshot.identity.parcelNodeId})`);
  if (snapshot.identity.district) lines.push(`- Base zoning district: ${snapshot.identity.district}`);
  if (snapshot.identity.overlay) lines.push(`- Overlay: ${snapshot.identity.overlay}`);
  lines.push("");

  // Selected scenario + certificate -------------------------------------------
  if (scenario && certificate) {
    lines.push(`## Selected scenario — ${scenario.label}`);
    lines.push("");
    lines.push(`- Scenario: \`${scenario.id}\``);
    lines.push(`- Solver: ${scenario.solverVersion}`);
    for (const metric of scenario.metrics) {
      lines.push(`- ${metric.label}: ${quantityText(metric.value)}`);
    }
    lines.push(
      `- Modeled ceilings (homes): legal density ${snapshot.ceilings.legalDensity ?? "—"} · massing ${snapshot.ceilings.massing} · physical site area budget ${snapshot.ceilings.physicalSiteAreaBudget} · overall ${snapshot.ceilings.overall}`,
    );
    lines.push("");
    lines.push("### Scenario certificate");
    lines.push("");
    lines.push(`- Certificate: \`${certificate.id}\``);
    lines.push(`- Freshness: ${certificate.freshness}`);
    lines.push(`- Pinned dependencies: ${certificate.dependencyCount}`);
    if (certificate.freshnessReasons.length > 0) {
      for (const reason of certificate.freshnessReasons) lines.push(`  - ${reason}`);
    }
    lines.push("");
  }

  // Key law --------------------------------------------------------------------
  lines.push("## Key law applied (LAW and APPLIES HERE kept separate)");
  lines.push("");
  const executable = snapshot.constraints.filter((constraint) => constraint.executable);
  if (executable.length === 0) {
    lines.push("- No executable law recorded for this property.");
  }
  for (const constraint of executable) {
    const lawClaim = snapshot.claims.find((claim) => claim.id === constraint.lawClaimId);
    const lawSource = snapshot.sources.find((source) => source.id === constraint.lawSourceId);
    const appliesClaim = snapshot.claims.find((claim) => claim.id === constraint.appliesHereClaimId);
    const appliesSource = snapshot.sources.find((source) => source.id === constraint.appliesHereSourceId);
    const regulation = snapshot.regulations.find((entry) => entry.id === constraint.regulationId);
    lines.push(`- **${constraint.valueSummary}** (\`${constraint.id}\`)`);
    if (regulation) lines.push(`  - Locator: ${regulation.codeSection}`);
    if (lawSource) {
      lines.push(
        `  - LAW: ${sourceLabel(lawSource.title, lawSource.authority)}, retrieved ${lawSource.retrievedAt.slice(0, 10)}`,
      );
    }
    if (lawClaim?.verbatimQuote) lines.push(`  - Quoted: “${lawClaim.verbatimQuote}”`);
    if (appliesClaim && appliesSource) {
      lines.push(
        `  - APPLIES HERE: ${appliesClaim.valueSummary} per ${sourceLabel(appliesSource.title, appliesSource.authority)}`,
      );
    }
  }
  lines.push("");

  // Mission constraints ----------------------------------------------------------
  lines.push("## Mission rules (user-declared — not sourced external facts)");
  lines.push("");
  if (snapshot.missions.length === 0) {
    lines.push("- No mission rules confirmed for this property.");
  }
  for (const mission of snapshot.missions) {
    lines.push(`- ${mission.normalizedSummary} — “${mission.intentText}” (\`${mission.id}\`, ${mission.hardOrSoft})`);
  }
  lines.push("");

  // Assumptions -------------------------------------------------------------------
  lines.push("## Assumptions (modeler-declared planning inputs)");
  lines.push("");
  for (const assumption of snapshot.assumptions) {
    lines.push(`- ${assumption.statement} — ${assumption.valueSummary} (\`${assumption.id}\`)`);
    lines.push(`  - Rationale: ${assumption.rationale}`);
  }
  lines.push("");

  // Conflicts -----------------------------------------------------------------------
  lines.push("## Conflicts");
  lines.push("");
  if (snapshot.conflicts.length === 0) {
    lines.push("- No unresolved conflicts among the captured sources for this property.");
  }
  for (const conflict of snapshot.conflicts) {
    lines.push(`- ${conflict.semanticRuleKey} — ${conflict.explanation}`);
    for (const member of conflict.members) {
      lines.push(
        `  - ${member.valueSummary} per ${member.sourceRef} (${AUTHORITY_LABEL[member.authority] ?? member.authority}, ${member.retrievedAt.slice(0, 10)})`,
      );
    }
    lines.push(`  - Compiler resolution: ${conflict.resolution}`);
  }
  lines.push("");

  // Unresolved questions ---------------------------------------------------------------
  lines.push("## Unresolved — professional review required");
  lines.push("");
  const openReviews = snapshot.expertReviews.filter((review) => review.reviewStatus === "OPEN" || review.reviewStatus === "IN_REVIEW");
  for (const review of openReviews) {
    lines.push(`- [${review.category}] ${review.question}`);
    lines.push(`  - Why it matters: ${review.whyItMatters} (${review.severity})`);
  }
  const computationQuestions = snapshot.computationQuestions.filter(
    (question) => scenario && question.scenarioId === scenario.id,
  );
  if (computationQuestions.length > 0) {
    lines.push("");
    lines.push("### Deterministic checks this scenario could not evaluate");
    lines.push("");
    for (const question of computationQuestions) {
      lines.push(`- ${question.label}: ${question.status}. ${question.explanation}`);
    }
  }
  lines.push("");

  // Sources --------------------------------------------------------------------------------
  lines.push("## Sources");
  lines.push("");
  lines.push("| Source | Publisher | Authority | Retrieved |");
  lines.push("|---|---|---|---|");
  for (const source of snapshot.sources) {
    lines.push(
      `| ${source.title} | ${source.publisher} | ${AUTHORITY_LABEL[source.authority] ?? source.authority} | ${source.retrievedAt.slice(0, 10)} |`,
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `Generated by Acrevia ${snapshot.projectionVersion} · solver ${snapshot.identity.solverVersion || "—"} · snapshot of project ${snapshot.identity.projectId}.`,
  );
  lines.push("");
  return lines.join("\n");
}
